spring:
  application:
    name: Arcane

  datasource :
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/arcane_db?serverTimezone=Asia/Seoul}
    username : ${SPRING_DATASOURCE_USERNAME:root}
    password : ${SPRING_DATASOURCE_PASSWORD:arcane1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa :
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
server:
  port : 8080

jwt:
  secret: ArcaneArcaneArcaneArcaneArcaneArcane88534Arcane
  expiration : 3600000

riot:
  # 이게 진짜임
  api-key: RGAPI-3b82fdf6-9dcf-4168-bf12-05f31dcf76d5

  # puuid1
  api-key-temp1: RGAPI-67436fcf-7f21-4fe7-9826-6fda22cbe565
  api-key-temp2: RGAPI-0d21c393-8bc5-4b92-8551-c18b734b2e2e
  api-key-temp3: RGAPI-a69992ee-8fb2-4f8e-83cb-293ab1dd6ae9
  api-key-temp4: RGAPI-7e132b89-6a71-4964-ad50-56a2d9d43007


  patch-version : 15.24.1
  season2024-1 : 1704844800
  season2024-2 : 1715731200
  season2025-1 : 1736434800
  season2025-2 : 1746019200
  season2025-3 : 1756281600

modeling:
  python-url: ${MODELING_PYTHON_URL:http://localhost:8864}
